sudo: required
dist: trusty

language: haxe

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.2"

script:
  - haxe geometrize-website.hxml debug.hxml
  - haxe geometrize-website.hxml release.hxml